version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          TAG=1.$CIRCLE_BUILD_NUM
          docker build -t srnd/codeday-present:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push srnd/codeday-present:$TAG
